package PokeZoo.JUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.security.auth.login.AccountNotFoundException;

import org.junit.jupiter.api.Test;

import PokeZoo.bbdd.manager.ManagerFile;
import PokeZoo.bbdd.manager.ManagerFood;
import PokeZoo.bbdd.pojo.Food;

class FileTest {

	private ManagerFile managerFile = new ManagerFile();
	private ManagerFood managerFood = new ManagerFood();

	@Test
	void testFileCreationAndRead() {
		try {
			File newFile = managerFile.createFile(5, 5.0);

			String textFromFile = managerFile.readFile(newFile);
			
			String expectedText = "Cantidad de entradas: 5Precio: 25.0€";

			assertEquals(textFromFile, expectedText);

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	@Test
	void testFileArrayList() {
		ArrayList<Food> allFood = null;
		try {
			allFood = managerFood.selectAll();
		} catch (Exception e) {
			// Nothing
		}

		try {
			File newFile = managerFile.createFileTestFood(allFood);
			
			String textFromFile = managerFile.readFile(newFile);

			String expectedText = "	idFood: 1"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: ZumoBaya"
					+ ""
					+ "	descriptionFo: Restaura 10 PS"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 2"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Dorada"
					+ ""
					+ "	descriptionFo: Restaura 30 PS"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 3"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Bayamarga"
					+ ""
					+ "	descriptionFo: Cura la confusión"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 4"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: AntiquemBaya"
					+ ""
					+ "	descriptionFo: Descongle a un Pokémon"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 5"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Hielo"
					+ ""
					+ "	descriptionFo: Cura las quemaduras"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 6"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Menta"
					+ ""
					+ "	descriptionFo: Despierta al Pokémon"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 7"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Antiparabaya"
					+ ""
					+ "	descriptionFo: Cura la parálisis"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 8"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Bayantídoto"
					+ ""
					+ "	descriptionFo: Cura el envenenamiento"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 9"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Milagro"
					+ ""
					+ "	descriptionFo: Cura cualquier alteración del estado"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 10"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Misterio"
					+ ""
					+ "	descriptionFo: Restaura 5 PP de un ataque"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 11"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Zreza"
					+ ""
					+ "	descriptionFo: Cura la parálisis"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 12"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Atania"
					+ ""
					+ "	descriptionFo: Despierta al Pokémon"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 13"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Meloc"
					+ ""
					+ "	descriptionFo: Cura el envenenamiento"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 14"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Safre"
					+ ""
					+ "	descriptionFo: Cura las quemaduras"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 15"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Perasi"
					+ ""
					+ "	descriptionFo: Cura el congelamiento"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 16"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Zanama"
					+ ""
					+ "	descriptionFo: Restaura 10 PP"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 17"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Aranja"
					+ ""
					+ "	descriptionFo: Restaura 10 PS"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 18"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Caquic"
					+ ""
					+ "	descriptionFo: Cura la confusión"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 19"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Ziuela"
					+ ""
					+ "	descriptionFo: Cura cualquier alteración de estado"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 20"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Zidra"
					+ ""
					+ "	descriptionFo: Restaura 30 PS"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 21"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Higog"
					+ ""
					+ "	descriptionFo: Restaura 1/8 de los PS pero confunde si al Pokémon no le gusta el sabor picante"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 22"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Wiki"
					+ ""
					+ "	descriptionFo: Restaura 1/8 de los PS pero confunde si al Pokémon no le gusta el sabor seco"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 23"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Ango"
					+ ""
					+ "	descriptionFo: Restaura 1/8 de los PS pero confunde si al Pokémon no le gusta el sabor dulce"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 24"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Guaya"
					+ ""
					+ "	descriptionFo: Restaura 1/8 de los PS pero confunde si al Pokémon no le gusta el sabor amargo"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 25"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Pabaya"
					+ ""
					+ "	descriptionFo: Restaura 1/8 de los PS pero confunde si al Pokémon no le gusta el sabor ácido"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 26"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Frambu"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 27"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Oram"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 28"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Latano"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 29"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Peragu"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 30"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Pinia"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 31"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Grana"
					+ ""
					+ "	descriptionFo: Hace que el Pokémon sea amistoso, pero baja puntos de esfuerzo de PS (sólo Esm). Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 32"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Algama"
					+ ""
					+ "	descriptionFo: Restaura 10 PS"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 33"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Monji"
					+ ""
					+ "	descriptionFo: Hace que el Pokémon sea amistoso, pero baja puntos de esfuerzo de At. (sólo Esm). Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 34"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Ispero"
					+ ""
					+ "	descriptionFo: Hace que el Pokémon sea amistoso, pero baja puntos de esfuerzo de Def. (sólo Esm). Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 35"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Meluce"
					+ ""
					+ "	descriptionFo: Hace que el Pokémon sea amistoso, pero baja puntos de esfuerzo de AtEsp. (sólo Esm). Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 36"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Uvav"
					+ ""
					+ "	descriptionFo: Hace que el Pokémon sea amistoso, pero baja puntos de esfuerzo de DefEsp. (sólo Esm). Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 37"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Tamate"
					+ ""
					+ "	descriptionFo: Hace que el Pokémon sea amistoso, pero baja puntos de esfuerzo de Vel. (sólo Esm). Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 38"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Mais"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 39"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Aostan"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 40"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Rautan"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 41"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Monli"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 42"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Wikano"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 43"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Plama"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 44"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Sambia"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 45"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Rudion"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 46"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Andano"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 47"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Lichi"
					+ ""
					+ "	descriptionFo: Aumenta el At. cuando los PS están por debajo de 1/3"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 48"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Gonlan"
					+ ""
					+ "	descriptionFo: Aumenta la Def. cuando los PS están por debajo de 1/3"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 49"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Aslac"
					+ ""
					+ "	descriptionFo: Aumenta la Vel. cuando los PS están por debajo de 1/3"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 50"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Yapati"
					+ ""
					+ "	descriptionFo: Aumenta el AtEsp. cuando los PS están por debajo de 1/3"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 51"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Aricoc"
					+ ""
					+ "	descriptionFo: Aumenta la DefEsp. cuando los PS están por debajo de 1/3"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 52"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Zonlan"
					+ ""
					+ "	descriptionFo: Aumenta la posibilidad de dar un golpe crítico cuando los PS están por debajo de 1/3"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 53"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Arabol"
					+ ""
					+ "	descriptionFo: Aumenta cualquier stat cuando los PS están por debajo de 1/3"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 54"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 100"
					+ ""
					+ "	nameFo: Baya Enigma"
					+ ""
					+ "	descriptionFo: Sirve para hacer Pokécubos. Restaura 1/4 de los PS máximos cuando el Pokémon es afectado por ataques supereficaces"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 59"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 20"
					+ ""
					+ "	nameFo: BayaPepe"
					+ ""
					+ "	descriptionFo: jajaja"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 60"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 20"
					+ ""
					+ "	nameFo: BayaPepe"
					+ ""
					+ "	descriptionFo: jajaja"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 61"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 20"
					+ ""
					+ "	nameFo: BayaPepe"
					+ ""
					+ "	descriptionFo: jajaja"
					+ ""
					+ ""
					+ ""
					+ "	idFood: 62"
					+ ""
					+ "	quantityFo: 500"
					+ ""
					+ "	dailyConsumeFo: 20"
					+ ""
					+ "	nameFo: BayaPepe"
					+ ""
					+ "	descriptionFo: jajaja"
					+ ""
					+ ""
					+ ""
					+ "";

			assertEquals(textFromFile, expectedText);
		} catch (IOException e) {
			// Nothing
		}

	}

}
